---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network
  labels:
    app: network
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: network
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: network
    spec:
      volumes:
        - name: nas
          persistentVolumeClaim:
            claimName: monitoring.network.www-probe.pvc
      containers:
        - image: local.registry/skwr/monitoring/www-probe
          name: www-probe
          env:
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: send-grid
                  key: API_KEY
          envFrom:
            - configMapRef:
                name: network.www-probe.env
          volumeMounts:
            - mountPath: "/opt/module/data"
              name: nas
