---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-internet-probe-pv
  labels:
    app: internet-probe
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/nas/monitoring-internet-probe
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-internet-probe-pvc
  labels:
    app: internet-probe
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: monitoring-internet-probe-pv
