---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.network.www-probe.pv
  labels:
    app: network
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/nas/monitoring/network/www-probe
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring.network.www-probe.pvc
  labels:
    app: network
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: monitoring.network.www-probe.pv
